/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pucp.gamesoft.rrhh.views;

import java.rmi.RemoteException;
import java.util.ArrayList;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import pucp.gamesoft.rrhh.controller.dao.DAODepartment;
import pucp.gamesoft.rrhh.controller.dao.DAOEmployee;
import pucp.gamesoft.rrhh.model.Department;
import pucp.gamesoft.rrhh.model.Employee;

/**
 *
 * @author Usuario
 */
public class employeeForm extends javax.swing.JFrame {

    /**
     * Creates new form employeeForm
     */
    DAODepartment daoDepartment;
    DAOEmployee daoEmployee;
    public employeeForm() {
        initComponents();
        try{
            System.setProperty("java.rmi.server.hostname","10.100.88.169");
            daoDepartment=(DAODepartment)java.rmi.Naming.lookup("//10.100.88.169:1235/daoDepartment");
            daoEmployee = (DAOEmployee)java.rmi.Naming.lookup("//10.100.88.169:1235/daoEmployee");
            
            ArrayList<Department> listDepartments = new ArrayList<Department>();
            listDepartments = daoDepartment.queryAllIndependent(); //luegoAllDependent
             
            DefaultMutableTreeNode root = new DefaultMutableTreeNode("Empleados");
            
            establecerJerarquiaDepartment(root,listDepartments);
            DefaultTreeModel modelo = new DefaultTreeModel(root);
            
            treeEmployee.setModel(modelo);
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        treeEmployee = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(treeEmployee);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   private void establecerJerarquiaDepartment(DefaultMutableTreeNode raiz, ArrayList<Department> departments) throws RemoteException{
        for(Department d : departments){
            DefaultMutableTreeNode node = new DefaultMutableTreeNode(d);
                        
            ArrayList<Employee> employees = new ArrayList<Employee>();
            ArrayList<Department> subDepartments = new ArrayList<Department>();
            
                    
            
            employees = daoEmployee.queryAllIndependent(d.getId());
            establecerJerarquiaEmployee(node, employees);
            
            raiz.add(node);
            
            subDepartments = daoDepartment.queryAllDependent(d.getId());
            establecerJerarquiaDepartment( node, subDepartments );
                   
            
                
        }
    }
    
    private void establecerJerarquiaEmployee(DefaultMutableTreeNode raiz, ArrayList<Employee> employees) throws RemoteException{
        for(Employee e: employees){
            DefaultMutableTreeNode node = new DefaultMutableTreeNode(e);
                  
            ArrayList<Employee> subemployees = new ArrayList<Employee>();
                        
                     
            subemployees = daoEmployee.queryAllDependent(e.getId());
            establecerJerarquiaEmployee( node,  subemployees );
            raiz.add(node);
               
        }
    }
    
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree treeEmployee;
    // End of variables declaration//GEN-END:variables
}
